server:
  port: 8050
spring:
  application:
    name: spectre-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eacdy/spring-cloud-study/
          search-paths: config-repo
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:2915/eureka/
